### ISSUE TITLE
Total time doesn't always add up correctly

### ISSUE THREAD

**Issue by TookiTheGreat** [vyleung/logseq-time-tracker-plugin#6]
I love the functionality your plugin provides but lately I have been having some issues with the total time calculations: when I use the refresh button, or use the menu option to 'get/update total time tracked' I regularly get a wrong result. When pressing the refresh button several times in a row, the result seems to cycle through a range of totals, only one of which is the correct one.
Can it be an issue with the way I build up the tree of things to be tracked?
For instance, I have a tree that looks like this:
Client
time-tracked-total: hh:mm:ss
* Interviews
  * Interview 1
     time-tracked 01:00:00
  * Interview 2
     time-tracked 01:00:00
     * Feedback 2
       time-tracked 00:30:00
  * ...
  * Interview x
       time-tracked 01:00:00
* Meetings
  * Meeting 1
     time-tracked 01:00:00
  * Meeting 2
     time-tracked 01:00:00
  * ...
  * Meeting x
       time-tracked 01:00:00

etc.

The 'time-tracked-total' under the top node has become unreliable lately.

Warm regards,

Bard

**Comment by vyleung** [comment]
hi Bard, thanks for providing a detailed example. this is also something that I've also noticed, so your tree structure isn't the problem. I'll work on refactoring the get/updated total time tracked function to fix this issue

**Comment by TookiTheGreat** [comment]
Hi Vyleung (I hope I got your name right),

Cool. Best of luck with the refactoring. Your plugin is one of the few tools that really helps me keep track of the hours I spend on the many different clients I have. So, I owe you one. If I can donate a coffee (or something similar), let me know.

**Comment by TookiTheGreat** [comment]
I just saw the email with your comment and see you are a Vivian. So, sorry for getting your name wrong, Vivian. I guess I owe you two coffees now.

**Comment by vyleung** [comment]
happy to hear you find the plugin useful! i appreciate your offer to donate a coffee - you can do so [here](https://www.buymeacoffee.com/vyleung) 🙂

**Comment by TookiTheGreat** [comment]
Done.

**Comment by vyleung** [comment]
this issued should be fixed in [v.2.1.1](https://github.com/vyleung/logseq-time-tracker-plugin/releases/tag/v.2.1.1)
